---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://api.stackbit.com/project/5d396f6f9a0cd6001026af62/webhook/forestry
sections:
- type: document
  path: site-metadata.json
  label: Global Site Config
  templates:
  - config
- type: document
  path: src/data/social.json
  label: Social Links
  templates:
  - social
- type: document
  path: src/data/author.json
  label: Author
  templates:
  - author
- type: document
  path: src/pages/index.md
  label: Home
  templates:
  - home
- type: document
  path: src/pages/pricing.md
  label: Pricing
  templates:
  - pricing
- type: document
  path: src/pages/features.md
  label: Features
  templates:
  - features
- type: document
  path: src/pages/blog/index.md
  label: Blog
  templates:
  - blog
- type: document
  path: src/pages/contact.md
  label: Contact
  templates:
  - contact
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "{posts/**,index.md,pricing.md,features.md,blog/index.md,contact.md}"
  templates:
  - page
- type: directory
  path: src/pages/posts
  label: Posts
  create: all
  match: "**/*"
  templates:
  - post
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: gatsby build
  publish_command: gatsby build
  preview_output_directory: public
  output_directory: public
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
