---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 'https://api.stackbit.com/project/5d396f6f9a0cd6001026af62/webhook/forestry'
sections:
  - type: document
    label: Global Site Config
    path: site-metadata.json
    templates:
      - config
  - type: document
    label: Social Links
    path: src/data/social.json
    templates:
      - social
  - type: document
    label: Author
    path: src/data/author.json
    templates:
      - author
  - type: document
    label: Home
    path: src/pages/index.md
    templates:
      - home
  - type: document
    label: Pricing
    path: src/pages/pricing.md
    templates:
      - pricing
  - type: document
    label: Features
    path: src/pages/features.md
    templates:
      - features
  - type: document
    label: Blog
    path: src/pages/blog/index.md
    templates:
      - blog
  - type: document
    label: Contact
    path: src/pages/contact.md
    templates:
      - contact
  - type: directory
    path: src/pages
    match: '**/*'
    exclude: '{posts/**,index.md,pricing.md,features.md,blog/index.md,contact.md}'
    label: Pages
    create: all
    templates:
      - page
  - type: directory
    path: src/pages/posts
    match: '**/*'
    label: Posts
    create: all
    templates:
      - post
upload_dir: static/images
public_path: /images
front_matter_path: ''
use_front_matter_path: false
file_template: ':filename:'
